### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ghost** [ezerssss/uprev#1]
* options for flashcards (keyword, definition, alternate)
* private and public option for posting of quizzes/flashcards
* unfinished quiz/flashcards posted as drafts (private)
* adding filters for quizzes/flashcards (creator, date, etc.)

**Comment by ezerssss** [comment]
~~unfinished quiz/flashcards posted as drafts (private)~~

Draft system:
Save draft to locatStorage every `3 MINUTES`
Works for both Quiz and Flashcard

Commit reference: https://github.com/ezerssss/uprev/commit/1545656c4fd854de8e0c61e31c4a03c304dac61a

**Comment by ezerssss** [comment]
~~options for flashcards (keyword, definition, alternate)~~

![image](https://user-images.githubusercontent.com/72904036/198586211-45698d9f-9099-4231-ae03-318736277ec5.png)

Flashcards Mode: `Random` `Description` `Keyword`

Commit reference: https://github.com/ezerssss/uprev/commit/632150a8c7a0f12856a9a15553e02d15e671f613

**Comment by ezerssss** [comment]
Regarding the public and private posting of quizzes and flashcards, I won't implement them as the purpose of the site is to share your notes and knowledge to other students.

Filters for the quiz and flashcards list will be done later when there is a need to do so (currently we only have very few quizzes and flashcards so it doesn't matter as of now). I will open a separate issue for this so that we can keep track of it https://github.com/ezerssss/uprev/issues/2.
